
const eums={
	BIKE_FAULT_HEALTH:0,//健康
	BIKE_FAULT_TYPE_X_KONG_ZHI_QI:1000, //控制器故障
	BIKE_FAULT_TYPE_X_KONG_ZHI_QI_JIN_SHUI_DUAN_LU:1001, //控制器故障, 进水短路 
	BIKE_FAULT_TYPE_X_KONG_ZHI_QI_GONG_NENG:1002, //控制器故障, 功能故障 
	BIKE_FAULT_TYPE_X_DIAN_JI:1100, //电机故障,
	BIKE_FAULT_TYPE_X_DIAN_JI_XIAN_LU:1101, //电机故障,线路故障
	BIKE_FAULT_TYPE_X_DIAN_JI_GAI_LIE:1102, //电机故障,盖子裂了
	BIKE_FAULT_TYPE_X_DIAN_JI_GONG_NENG:1103, //电机故障, 功能故障 
	BIKE_FAULT_TYPE_X_SHA_CHE:1200, //刹车
	BIKE_FAULT_TYPE_X_SHA_CHE_QIAN:1201, //刹车-前刹
	BIKE_FAULT_TYPE_X_SHA_CHE_HOU:1202, //刹车-后刹
	BIKE_FAULT_TYPE_X_SHA_CHE_XIAN:1203, //刹车-莎车县
	BIKE_FAULT_TYPE_X_SHA_CHE_DIAO_JIE:1204 //刹车-不能调节
}
export {eums}
